title: Site
unlisted: true

tabs:
  main:
    label: Content
    icon: page
    sections:
      pages: true
  seotab: seo
  menus:
    icon: menu
    fields:
      primarynav:
        extends: fields/singlemenu
        label: Primary navigation
      footernav:
        extends: fields/multiplemenu
        label: Footer navigations
        max: 4
